import {initialBoard,moves,apply,coord,positionKey} from './engine.js';
const $=s=>document.querySelector(s),names={1:'สีงาช้าง','-1':'สีดำ'},storageKey='thai-checkers-v1';
let board=initialBoard(),side=1,mode='ai',depth=4,history=[],positions=[positionKey(board,side)],result='',selected=null,prefix=[],thinking=false,job=0,worker;
try{const saved=JSON.parse(localStorage.getItem(storageKey));if(saved&&saved.board?.length===64&&saved.board.every(p=>[-2,-1,0,1,2].includes(p))&&[1,-1].includes(saved.side)&&['ai','local'].includes(saved.mode)&&Array.isArray(saved.history)&&saved.history.every(h=>typeof h==='string')&&Array.isArray(saved.positions)&&typeof saved.result==='string'){({board,side,mode,history,positions,result}=saved);}}catch{}
$('#app').innerHTML=`<header><a class="brand" href="./"><span class="brand-mark">◉</span><span>หมากฮอสไทย<small>THAI CHECKERS</small></span></a><span class="edition">กระดานเล็ก · เกมคิดไกล</span></header><main><section class="play-area" aria-label="กระดานเกม"><div class="player-bar"><span><i class="mini black"></i> สีดำ <small id="opponent"></small></span><span id="black-count"></span></div><div class="board-frame"><div id="board" class="board" role="group" aria-label="กระดานหมากฮอส 8 คูณ 8"></div></div><div class="player-bar"><span><i class="mini ivory"></i> สีงาช้าง <small>เดินก่อน</small></span><span id="ivory-count"></span></div><p class="board-hint">เลือกหมาก แล้วเลือกช่องที่มีจุด · สัญลักษณ์ ♛ คือฮอส</p></section><aside><div class="eyebrow">ตาของคุณ</div><h1 id="status" aria-live="polite"></h1><p id="message" class="message" aria-live="polite"></p><div class="settings"><label for="mode">รูปแบบการเล่น</label><select id="mode"><option value="ai">เล่นกับ AI</option><option value="local">เล่น 2 คนบนเครื่องเดียว</option></select><label for="level">ระดับ AI</label><select id="level"><option value="2">ง่าย · ฝึกเดิน</option><option value="4" selected>ปกติ · ฝึกวางแผน</option><option value="6">ยาก · คิดล่วงหน้า</option></select></div><div class="actions"><button id="new" class="primary">เริ่มเกมใหม่</button><button id="resign">ยอมแพ้</button></div><div id="confirm" hidden class="confirm"><p id="confirm-text"></p><button id="yes" class="primary">ยืนยัน</button><button id="no">ยกเลิก</button></div><section class="record"><h2>บันทึกการเดิน <span id="turn-count">0 ตา</span></h2><ol id="history" aria-label="ประวัติการเดิน"></ol></section><details><summary>กติกาหมากฮอสไทย</summary><ul><li>ฝ่ายละ 8 ตัว เดินบนช่องเข้ม สีงาช้างเริ่มก่อนในเกมนี้</li><li>หมากธรรมดาเดินและกินเฉียงไปข้างหน้าเท่านั้น</li><li>หากกินได้ต้องกิน และต้องกินต่อด้วยตัวเดิมจนจบ เลือกเส้นทางได้ ไม่บังคับกินมากที่สุด</li><li>ถึงแถวสุดท้ายเป็นฮอสและจบตา ฮอสเดินเฉียงได้ไกลทั้งสองทิศ</li><li>ฮอสกินแล้วลงช่องว่างถัดจากตัวที่ถูกกินทันที นำตัวที่ถูกกินออกทันที</li><li>หมดหมากหรือไม่มีทางเดินถือว่าแพ้ เกมนี้เสมอเมื่อเกิดตำแหน่งเดิมและฝ่ายเดินเดิมครบ 3 ครั้ง</li></ul><a href="https://mindsports.nl/index.php/arena/draughts/500-thai-checkers" target="_blank" rel="noreferrer">อ่านกติกาอ้างอิง ↗</a></details><p class="saved">บันทึกเกมอัตโนมัติบนอุปกรณ์นี้</p></aside></main><footer>THAI CHECKERS <span>เล่นช้า ๆ คิดให้ไกล</span></footer>`;
$('#mode').value=mode;
function save(){try{localStorage.setItem(storageKey,JSON.stringify({board,side,mode,history,positions,result}));$('.saved').textContent='บันทึกเกมอัตโนมัติบนอุปกรณ์นี้';}catch{$('.saved').textContent='อุปกรณ์นี้ไม่อนุญาตให้บันทึกเกม';}}
function render(){
 const legal=moves(board,side),subset=prefix.length?legal.filter(m=>prefix.every((p,i)=>m.path[i]===p)):legal;
 const dest=new Set(selected===null?[]:subset.filter(m=>m.path[0]===(prefix[0]??selected)).map(m=>m.path[prefix.length||1]));
 const shown=board.slice();if(prefix.length>1){const sample=subset[0];shown[prefix[0]]=0;for(let n=0;n<prefix.length-1;n++)shown[sample.taken[n]]=0;shown[prefix.at(-1)]=board[prefix[0]];}
 $('#board').innerHTML=shown.map((p,i)=>{const dark=(Math.floor(i/8)+i%8)%2===1,active=!result&&!thinking&&(mode==='local'||side===1);return `<button class="square ${dark?'dark':'light'} ${i===selected?'selected':''} ${dest.has(i)?'destination':''}" data-i="${i}" aria-label="${coord(i)}${p?' '+names[Math.sign(p)]+(Math.abs(p)===2?' ฮอส':''):''}${dest.has(i)?' เดินได้':''}" aria-pressed="${i===selected}" ${!dark?'disabled':''}>${p?`<span class="piece ${p>0?'ivory':'black'} ${Math.abs(p)===2?'king':''}">${Math.abs(p)===2?'♛':''}</span>`:''}${i%8===0?`<span class="rank">${8-Math.floor(i/8)}</span>`:''}${i>=56?`<span class="file">${'abcdefgh'[i%8]}</span>`:''}</button>`;}).join('');
 $('#black-count').textContent=board.filter(p=>p<0).length+' ตัว';$('#ivory-count').textContent=board.filter(p=>p>0).length+' ตัว';$('#opponent').textContent=mode==='ai'?'AI':'ผู้เล่น 2';
 $('#status').textContent=result||(thinking?'AI กำลังคิด…':'ตา'+names[side]);$('.eyebrow').textContent=result?'จบเกม':mode==='ai'&&side===-1?'คู่แข่ง':'พร้อมเดิน';
 $('#message').textContent=result?'เริ่มเกมใหม่เพื่อลองอีกครั้ง':prefix.length>1?'ต้องกินต่อด้วยหมากตัวเดิม':legal[0]?.taken.length?'มีจังหวะกิน ต้องเลือกหมากที่กินได้':thinking?'กำลังพิจารณาตาถัดไป':'แตะหมากเพื่อดูช่องที่เดินได้';
 $('#history').replaceChildren();if(!history.length){const li=document.createElement('li');li.className='empty';li.textContent='การเดินแรกเริ่มที่คุณ';$('#history').append(li);}else history.forEach((h,i)=>{const li=document.createElement('li');li.textContent=`${i+1}. ${h}`;$('#history').append(li);});$('#history').scrollTop=$('#history').scrollHeight;
 $('#turn-count').textContent=history.length+' ตา';$('#level').disabled=mode!=='ai';$('#resign').disabled=!!result||thinking;save();
}
function commit(m){const p=board[m.path[0]];board=apply(board,m);history.push(names[side]+' '+m.path.map(coord).join(m.taken.length?' × ':' → ')+(Math.abs(p)===1&&Math.abs(board[m.path.at(-1)])===2?' ♛':''));side=-side;prefix=[];selected=null;positions.push(positionKey(board,side));if(!moves(board,side).length)result=names[-side]+'ชนะ';else if(positions.filter(k=>k===positions.at(-1)).length>=3)result='เสมอ · ตำแหน่งซ้ำ 3 ครั้ง';render();startAI();}
function startAI(){if(mode!=='ai'||side!==-1||result||thinking)return;thinking=true;const id=++job;render();worker?.terminate();worker=new Worker(new URL('./ai.worker.js',import.meta.url),{type:'module'});const fallback=()=>{if(id!==job)return;thinking=false;const m=moves(board,side)[0];if(m)commit(m);};worker.onerror=fallback;worker.onmessage=({data})=>{if(data.id!==job)return;thinking=false;if(data.error){fallback();return;}commit(data.move);};worker.postMessage({id,board,side,depth});}
$('#board').onclick=e=>{const button=e.target.closest('[data-i]');if(!button||result||thinking||(mode==='ai'&&side===-1))return;const i=Number(button.dataset.i),legal=moves(board,side);if(prefix.length){const candidates=legal.filter(m=>prefix.every((p,n)=>m.path[n]===p)&&m.path[prefix.length]===i);if(candidates.length){prefix.push(i);selected=i;if(candidates[0].path.length===prefix.length)commit(candidates[0]);else render();return;}if(prefix.length>1)return;}
 if(legal.some(m=>m.path[0]===i)){selected=i;prefix=[i];render();$('#board').querySelector(`[data-i="${i}"]`)?.focus();}};
$('#board').onkeydown=e=>{const deltas={ArrowUp:-8,ArrowDown:8,ArrowLeft:-1,ArrowRight:1};if(!(e.key in deltas))return;e.preventDefault();let i=Number(e.target.closest('[data-i]')?.dataset.i);do{i+=deltas[e.key];}while(i>=0&&i<64&&$('#board').querySelector(`[data-i="${i}"]`).disabled);$('#board').querySelector(`[data-i="${i}"]`)?.focus();};
let pending;
$('#board').addEventListener('click',e=>{if(!$('#confirm').hidden)e.stopImmediatePropagation();},true);
function confirmAction(text,action){$('#confirm-text').textContent=text;$('#confirm').hidden=false;pending=action;$('#yes').focus();}
$('#yes').onclick=()=>{$('#confirm').hidden=true;pending?.();pending=null;};$('#no').onclick=()=>{$('#confirm').hidden=true;pending=null;};
function reset(nextMode=mode){job++;worker?.terminate();thinking=false;board=initialBoard();side=1;mode=nextMode;history=[];positions=[positionKey(board,side)];result='';prefix=[];selected=null;$('#mode').value=mode;render();}
$('#new').onclick=()=>confirmAction('เริ่มเกมใหม่? เกมปัจจุบันจะถูกแทนที่',()=>reset());
$('#resign').onclick=()=>confirmAction('ยืนยันยอมแพ้ในเกมนี้?',()=>{result=names[-side]+'ชนะ · อีกฝ่ายยอมแพ้';selected=null;prefix=[];render();});
$('#mode').onchange=e=>{const next=e.target.value;e.target.value=mode;confirmAction('เปลี่ยนรูปแบบและเริ่มเกมใหม่?',()=>reset(next));};
$('#level').onchange=e=>{depth=Number(e.target.value);};render();startAI();
